### ISSUE TITLE
Is this working fine on urls like on subdomains?

### ISSUE THREAD

**Issue by 1br00** [sanjai-AK47/SubProber#2]
Hello, great tool, just want to ask is the purpose of the tool only for subdomains, can it filter alive domains from waybackruls, gau,  etc
This option should be added if not..

Kind regards, and really it's great tool

**Comment by sanjai-AK47** [comment]
Hi @1br00 , 
Subprober can used to probe for Urls also so you can also use it for that ,Thank you:)

**Comment by sanjai-AK47** [comment]
Thanks for creating issue and the issue is resolved now 😃
