### ISSUE TITLE
missing to probe some domain.

### ISSUE THREAD

**Issue by blackcodersec** [sanjai-AK47/SubProber#4]
here you can check.
![image](https://github.com/sanjai-AK47/SubProber/assets/72689232/7e90caca-3f5b-49d2-91a2-658c3dc3e2f4)

**Comment by sanjai-AK47** [comment]
Hey @blackcodersec , 
Thank you for this and I want to inform that I'm already aware of this problem and Im still in development of subprober to resolve this issue, soon I will make a update on this issue thank you for this :)

**Comment by blackcodersec** [comment]
Is it possible to show redirected domain like `fhc` output.

![image](https://github.com/sanjai-AK47/SubProber/assets/72689232/bb7ba32f-0c9a-4467-85b0-392025c3afe1)

**Comment by sanjai-AK47** [comment]
Hey @blackcodersec ,

Since the both tools are build for different purpose and these output will be not same but you can get more information from subprober , you can see in your output how the both redirected location urls are different , unlike `fhc`,  `subprober` gives output differently not same as the `fhc`.

**Comment by blackcodersec** [comment]
Hey @sanjai-AK47,

I know both tools are build for different purpose and these outputs are not same.
but I use `subprober` for `httpx` & `httprobe` alternative script. that's why I said is this possible or not.
actually, I like python script, that's why I check your script and created the issue, but I think it increases the feature of your script.
okay, no problem.
`fhc` doing good.

**Comment by sanjai-AK47** [comment]
Hey @blackcodersec , 

Thanks for providing information about your needs, Subprober can't give output like the `fhc` , if I made those changes means it will also affect entire subprober outputs so sorry to say subprober cannot give output like this but after looking on your provided img , I can make this update on another tool `httprober`. if you have other issues means please submit it and thanks for showing your intrest on my tools.I want to clear one more thing is enabling `-ar` will make subprober to follow redirection and give results of redirected domain only and to know that I updated subprober with `-l` and `-ar` flags

**Comment by blackcodersec** [comment]
I saw your `httprober` script. There are not available function like `subprober`. That's why I use your `subprober` script.
Ok, as your wish :)

**Comment by blackcodersec** [comment]
Hey @sanjai-AK47 ,

Is it possible to implement `-dhp`,`-ar`,`-px`,`-das`,`-to`,`-mc`,`-ex` on the `httprober` script?
I think it would be good.

Another thing is the accuracy and concurrency of `httpprober` as the `subprober` script?

**Comment by sanjai-AK47** [comment]
Hey @blackcodersec ,
really appreciate your ideas but httprober is simple probing tool for replacement of  tomnomnom's httprobe, Since httprobe ris running on traditional threading, It will be updated to asychoronous performance and its not possible to add those features in that.

**Comment by blackcodersec** [comment]
Ok no problem :)

**Comment by sanjai-AK47** [comment]
completed this issue thank you
